### PR TITLE
Use npm module static-eval instead of static-eval2

### PR DESCRIPTION
**Pull request by jagonzalr**
Updates `package.json` to use `static-eval` instead of `static-eval2` since `static-eval` has been updated to fix [vulnerability](https://github.com/browserify/static-eval/commit/32f8efd072625e267aa7237d2daff35738c50d2a).

@goto-bus-stop

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
thanks! the `require()` call in index.js also needs to be changed back.

**Comment by jagonzalr** [comment]
@goto-bus-stop done :)

**Comment by jagonzalr** [comment]
@goto-bus-stop thanks for the merge. Can we do a version bump for npm?

**Comment by goto-bus-stop** [comment]
:package: 3.0.2

**Pull request merged**
